Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowedMethods:
    - sig
    - proc
    - it
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Style/StringLiterals:
  EnforcedStyle: double_quotes
