Style/BlockDelimiters:
  EnforcedStyle: semantic
  AllowedMethods:
    - sig
    - proc
    - it
Layout/CaseIndentation:
  EnforcedStyle: end
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
