#!/bin/bash

EXPND=$HOME/expanded
COMPL=$HOME/completed
LOG=$HOME/.local/var/log/posttorrent.log
FIFO=$HOME/.local/tmp/seedboxsync.fifo
TIME=$(date +%Y.%m.%d\ %H:%M:%S)
SRC=$1
SAMSUNG="$HOME/Dropbox/Samsung Link/Videos"
ANJU="$HOME/Dropbox/For Anju"

if [[ ! -a "${SRC}" ]] ; then
	echo "[${TIME}] Changing name from ${SRC}" >> $LOG
	BASE=$(basename "${SRC}")
	SRC="${COMPL}/${BASE}"
	echo "[${TIME}] to ${SRC}"  >> ${LOG}
fi

echo "[${TIME}] Evaluating ${SRC}" >> ${LOG}
if [[ -d "${SRC}" ]] ; then
	RARFILE=$(find "${SRC}" -maxdepth 1 -name *.rar | head -1)
	if [[ -f "${RARFILE}" ]] ; then
		echo "[${TIME}] Extracting ${RARFILE}" >> ${LOG}
		unrar x -inul "${RARFILE}" ${EXPND}
#		echo "[${TIME}] Done" >> ${LOG}
	fi
fi

# Dropbox copy
shopt -qs nocasematch
if [[ "${SRC}" =~ Apprentice ]] ; then
	VIDFILE=$(find "${EXPND}" -iname "$(basename "${SRC}")*")
	ln "${VIDFILE}" "${ANJU}"
elif [[ "${SRC}" =~ British.*Bake ]] ; then
	VIDFILE=$(find "${EXPND}" -iname "$(basename "${SRC}")*")
	ln "${VIDFILE}" "${ANJU}"
elif [[ "${SRC}" =~ Desi.Rascals ]] ; then
	VIDFILE=$(find "${SRC}" -iname "*.mp4" -o -iname "*.mkv")
	ln "${VIDFILE}" "${ANJU}"
elif [[ "${SRC}" =~ W1A ]] ; then
	VIDFILE=$(find "${EXPND}" -iname "$(basename "${SRC}")*")
	ln "${VIDFILE}" "${ANJU}"
elif [[ "${SRC}" =~ Liberty.*London ]] ; then
	VIDFILE=$(find "${EXPND}" -iname "$(basename "${SRC}")*.mp4")
	ln "${VIDFILE}" "${ANJU}"
elif [[ "${SRC}" =~ Graham ]] ; then
	VIDFILE=$(find "${EXPND}" -iname "$(basename "${SRC}")*")
	ln "${VIDFILE}" "${ANJU}"
fi

if [[ -e ${FIFO} ]] ; then
#	echo "[${TIME}] Sending go" >> ${LOG}
	echo "${TIME}" > ${FIFO}
#	echo "[${TIME}] Done" >> ${LOG}
fi
