#!/bin/bash

EXPND=$HOME/expanded
COMPL=$HOME/completed
LOG=$HOME/.local/var/log/posttorrent.log
FIFO=$HOME/.local/tmp/seedboxsync.fifo
TIME=$(date +%Y.%m.%d\ %H:%M:%S)
SRC=$1
SAMSUNG="$HOME/Dropbox/Samsung Link/Videos"
ANJU="$HOME/Dropbox/For Anju"

if [[ ! -a "${SRC}" ]] ; then
	echo "[${TIME}] Changing name from ${SRC}" >> $LOG
	BASE=$(basename "${SRC}")
	SRC="${COMPL}/${BASE}"
	echo "[${TIME}] to ${SRC}"  >> ${LOG}
fi

#echo "[${TIME}] Evaluating ${SRC}" >> ${LOG}
if [[ -d "${SRC}" ]] ; then
	RARFILE=$(find "${SRC}" -maxdepth 1 -name *.rar | head -1)
	if [[ -f "${RARFILE}" ]] ; then
		echo "[${TIME}] Extracting ${RARFILE}" >> ${LOG}
		unrar x -inul "${RARFILE}" ${EXPND}
#		echo "[${TIME}] Done" >> ${LOG}
	fi
fi

# Dropbox copy
shopt -qs nocasematch
if [[ "${SRC}" =~ Apprentice ]] ||
		[[ "${SRC}" =~ British.Bake ]] ||
		[[ "${SRC}" =~ Big.Family.Cooking.Showdown ]] ||
		[[ "${SRC}" =~ Jamies.Quick.And.Easy.Food ]] ||
		[[ "${SRC}" =~ Victoria ]] ||
		[[ "${SRC}" =~ W1A ]] ||
		[[ "${SRC}" =~ Desi.Rascals ]] ; then
	VIDFILE="${SRC}"
	if [[ -d "${SRC}" ]] ; then
		VIDFILE=$(find "${SRC}" -iname "*.mp4" -o -iname "*.mkv")
	fi
	ln "${VIDFILE}" "${ANJU}"
fi

# if [[ "${SRC}" =~ Apprentice ]] ; then
	# ln "${SRC}" "${ANJU}"
# elif [[ "${SRC}" =~ British.*Bake ]] ; then
	# ln "${SRC}" "${ANJU}"
# elif [[ "${SRC}" =~ Big.Family.Cooking.Showdown ]] ; then
	# ln "${SRC}" "${ANJU}"
# elif [[ "${SRC}" =~ Jamies.Quick.And.Easy.Food ]] ; then
	# ln "${SRC}" "${ANJU}"
# elif [[ "${SRC}" =~ Victoria ]] ; then
	# ln "${SRC}" "${ANJU}"
# elif [[ "${SRC}" =~ W1A ]] ; then
	# ln "${SRC}" "${ANJU}"
# elif [[ "${SRC}" =~ Desi.Rascals ]] ; then
	# VIDFILE=$(find "${SRC}" -iname "*.mp4" -o -iname "*.mkv")
	# ln "${VIDFILE}" "${ANJU}"
# fi

if [[ -e ${FIFO} ]] ; then
#	echo "[${TIME}] Sending go" >> ${LOG}
	echo "${TIME}" > ${FIFO}
#	echo "[${TIME}] Done" >> ${LOG}
fi
